steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Build the project
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']  # Assuming you have a "build" script in your package.json

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'api-auth-cloud-run'  # Replace with your service name
      - '--source'
      - '.'  # The source of your app
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-west1'  # Replace with your desired region
      - '--set-env-vars'
      - 'GOOGLE_CLIENT_ID=$(gcloud secrets versions access latest --secret="google-client-id")'
      - '--set-env-vars'
      - 'GOOGLE_CLIENT_SECRET=$(gcloud secrets versions access latest --secret="google-client-secret")'
      - '--set-env-vars'
      - 'JWT_SECRET=$(gcloud secrets versions access latest --secret="jwt-secret")'
      - '--set-env-vars'
      - 'DATABASE_URL=$(gcloud secrets versions access latest --secret="database-url")'
      - '--set-env-vars'
      - 'NODE_ENV=production'  # Make sure to set the production environment

  # Step 4: Run the app in production mode using npm run start:prod
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'start:prod']  # This runs your app using 'node dist/main'

timeout: 1200s  # Optional: Set a timeout for the deployment process
