steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']  # Assuming you have a "build" script in your package.json

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
    - 'gcloud'
    - 'run'
    - 'deploy'
    - 'api-auth-cloud-run'
    - '--source'
    - '.'  # Deploy from the source directory
    - '--platform'
    - 'managed'
    - '--region'
    - 'us-west1'
    - '--set-env-vars'
    - 'GOOGLE_CLIENT_ID=$(gcloud secrets versions access latest --secret="google-client-id")'
    - '--set-env-vars'
    - 'GOOGLE_CLIENT_SECRET=$(gcloud secrets versions access latest --secret="google-client-secret")'
    - '--set-env-vars'
    - 'JWT_SECRET=$(gcloud secrets versions access latest --secret="jwt-secret")'
    - '--set-env-vars'
    - 'DATABASE_URL=$(gcloud secrets versions access latest --secret="database-url")'

timeout: 1200s  # Optional: Set a timeout for the deployment process
