steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']

  # Step 2: Generate Prisma client
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'prisma:generate']

  # Step 3: Build the project
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--source'
      - '.'
      - '--platform'
      - 'managed'
      - '--region'
      - '${LOCATION}'
      - '--set-env-vars'
      - 'NODE_ENV=${_NODE_ENV}'
      - '--set-env-vars'
      - 'GOOGLE_CALLBACK=${_GOOGLE_CALLBACK}'
      - '--set-env-vars'
      - 'POSTGRES_DB=${_POSTGRES_DB}'
      - '--set-env-vars'
      - 'POSTGRES_PORT=${_POSTGRES_PORT}'
      - '--set-env-vars'
      - 'POSTGRES_HOST=${_POSTGRES_HOST}'
      - '--set-secrets'
      - 'POSTGRES_USER=db_user:latest'
      - '--set-secrets'
      - 'POSTGRES_PASSWORD=db_password:latest'
      - '--set-env-vars'
      - 'DATABASE_URL=${_DATABASE_URL}'
      - '--set-secrets'
      - 'GOOGLE_CLIENT_ID=google_client_id:latest'
      - '--set-secrets'
      - 'GOOGLE_CLIENT_SECRET=google_client_secret:latest'
      - '--set-secrets'
      - 'JWT_SECRET=jwt_secret:latest'
      - '--add-cloudsql-instances'
      - '${PROJECT_ID}:${LOCATION}:${_POSTGRES_INSTANCE_NAME}'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '1'
      - '--network'
      - 'default'
      - '--subnet'
      - 'default'
      - '--vpc-egress'
      - 'all-traffic'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'services'
      - 'add-iam-policy-binding'
      - '${_SERVICE_NAME}'
      - '--region'
      - '${LOCATION}'
      - '--member'
      - 'allUsers'
      - '--role'
      - 'roles/run.invoker'

substitutions:
  _DATABASE_URL: "${_DATABASE_URL}"
  _POSTGRES_PORT: "${_POSTGRES_PORT}"
  _POSTGRES_DB: "${_POSTGRES_DB}"
  _POSTGRES_HOST: "${_POSTGRES_HOST}"
  _POSTGRES_INSTANCE_NAME: "${_POSTGRES_INSTANCE_NAME}"
  _GOOGLE_CALLBACK: "https://api.osposstore.com/auth/google/redirect"
  _NODE_ENV: "production"
  _SERVICE_NAME: "api-auth-cloud-run-v3"


options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

timeout: 1200s
